const quizQuestions = [
  { question: "What does “CC” stand for in email?", options: ["Carbon Copy", "Central Copy", "Computer Copy", "Common Copy"], answer: "A" },
  { question: "What is the purpose of BCC in email?", options: ["Hide recipient list", "Add attachment", "Send faster", "Encrypt message"], answer: "A" },
  { question: "What is IMAP used for?", options: ["Sending emails", "Receiving emails from server", "Blocking spam", "Encrypting emails"], answer: "B" },
  { question: "POP3 mainly does what?", options: ["Stores emails online", "Downloads emails to device", "Sends emails", "Blocks viruses"], answer: "B" },
  { question: "SMTP is used for:", options: ["Receiving emails", "Sending emails", "Storing emails", "Deleting emails"], answer: "B" },
  { question: "Which protocol allows access from multiple devices?", options: ["POP3", "IMAP", "SMTP", "FTP"], answer: "B" },
  { question: "What does “https” indicate?", options: ["Fast connection", "Secure connection", "Public access", "Offline mode"], answer: "B" },
  { question: "Which is NOT an email component?", options: ["Subject", "Body", "URL", "Recipient"], answer: "C" },
  { question: "Wi-Fi is an example of:", options: ["Wired network", "Wireless network", "Satellite network", "Cable network"], answer: "B" },
  { question: "Bluetooth is used for:", options: ["Long distance communication", "Short-range communication", "Internet hosting", "Data storage"], answer: "B" },
  { question: "DSL stands for:", options: ["Digital Subscriber Line", "Data Service Line", "Direct Server Link", "Digital Secure Line"], answer: "A" },
  { question: "ADSL provides:", options: ["Equal upload/download", "Faster download than upload", "Only upload", "No internet"], answer: "B" },
  { question: "Leased line is:", options: ["Temporary connection", "Shared network", "Dedicated connection", "Wireless connection"], answer: "C" },
  { question: "A virus is:", options: ["Hardware device", "Malicious software", "Network protocol", "Antivirus tool"], answer: "B" },
  { question: "A worm differs from a virus because:", options: ["Needs host file", "Self-replicates", "Cannot spread", "Is hardware"], answer: "B" },
  { question: "Spyware is used to:", options: ["Protect data", "Track user activity", "Speed internet", "Encrypt files"], answer: "B" },
  { question: "Spam refers to:", options: ["Useful emails", "Junk emails", "Encrypted emails", "Offline messages"], answer: "B" },
  { question: "Firewall is used to:", options: ["Increase speed", "Block unauthorized access", "Store files", "Send emails"], answer: "B" },
  { question: "Strong password should include:", options: ["Only letters", "Only numbers", "Letters, numbers, symbols", "Only symbols"], answer: "C" },
  { question: "Phishing is:", options: ["Fishing game", "Fake attempt to steal data", "Data backup", "Virus removal"], answer: "B" },
  { question: "E-commerce means:", options: ["Offline shopping", "Online buying and selling", "Banking only", "Data storage"], answer: "B" },
  { question: "B2B means:", options: ["Business to Buyer", "Business to Business", "Buyer to Buyer", "Bank to Business"], answer: "B" },
  { question: "B2C means:", options: ["Business to Customer", "Buyer to Company", "Customer to Business", "Company to Customer"], answer: "A" },
  { question: "C2C example is:", options: ["Amazon", "OLX", "Bank", "School"], answer: "B" },
  { question: "Shopping cart is used to:", options: ["Store money", "Store selected products", "Send emails", "Design websites"], answer: "B" },
  { question: "Digital wallet example:", options: ["PayPal", "Chrome", "Excel", "Gmail"], answer: "A" },
  { question: "UPI is used for:", options: ["Gaming", "Money transfer", "Email sending", "File storage"], answer: "B" },
  { question: "HTML stands for:", options: ["HyperText Markup Language", "HighText Machine Language", "Hyper Transfer Markup", "Home Tool Markup"], answer: "A" },
  { question: "Who created HTML?", options: ["Bill Gates", "Tim Berners-Lee", "Steve Jobs", "Mark Zuckerberg"], answer: "B" },
  { question: "HTML is used for:", options: ["Styling", "Structuring web pages", "Programming", "Database"], answer: "B" },
  { question: "Which tag defines the title?", options: ["<head>", "<title>", "<body>", "<html>"], answer: "B" },
  { question: "Which tag contains visible content?", options: ["<head>", "<body>", "<title>", "<meta>"], answer: "B" },
  { question: "Which tag creates paragraph?", options: ["<br>", "<p>", "<h1>", "<div>"], answer: "B" },
  { question: "Line break tag is:", options: ["<lb>", "<br>", "<break>", "<p>"], answer: "B" },
  { question: "Largest heading is:", options: ["<h6>", "<h1>", "<head>", "<h3>"], answer: "B" },
  { question: "Attributes are used to:", options: ["Delete content", "Add extra information", "Run programs", "Save files"], answer: "B" },
  { question: "Correct attribute format:", options: ["tag=value", "attribute=\"value\"", "value=attribute", "attribute:value"], answer: "B" },
  { question: "Anchor tag is used for:", options: ["Image", "Link", "Table", "Paragraph"], answer: "B" },
  { question: "Image tag is:", options: ["<img>", "<image>", "<pic>", "<src>"], answer: "A" },
  { question: "Bold text tag:", options: ["<i>", "<b>", "<u>", "<p>"], answer: "B" },
  { question: "Italic tag:", options: ["<i>", "<b>", "<u>", "<em>"], answer: "A" },
  { question: "Comment tag:", options: ["//", "<!-- -->", "/* */", "<comment>"], answer: "B" },
  { question: "Unordered list tag:", options: ["<ol>", "<ul>", "<li>", "<list>"], answer: "B" },
  { question: "Ordered list tag:", options: ["<ol>", "<ul>", "<li>", "<order>"], answer: "A" },
  { question: "List item tag:", options: ["<li>", "<ul>", "<ol>", "<item>"], answer: "A" },
  { question: "Table tag:", options: ["<table>", "<tr>", "<td>", "<th>"], answer: "A" },
  { question: "Table row tag:", options: ["<td>", "<tr>", "<th>", "<row>"], answer: "B" },
  { question: "Table cell tag:", options: ["<td>", "<tr>", "<th>", "<cell>"], answer: "A" },
  { question: "Header cell tag:", options: ["<td>", "<th>", "<tr>", "<head>"], answer: "B" },
  { question: "CSS stands for:", options: ["Creative Style Sheet", "Cascading Style Sheets", "Computer Style Sheet", "Color Style System"], answer: "B" },
  { question: "CSS is used for:", options: ["Structure", "Styling", "Database", "Security"], answer: "B" },
  { question: "Inline CSS is written:", options: ["External file", "Inside tag", "Server", "Database"], answer: "B" },
  { question: "Internal CSS is written in:", options: ["<body>", "<style>", "<html>", "<script>"], answer: "B" },
  { question: "External CSS uses:", options: ["<css>", "<link>", "<style>", "<script>"], answer: "B" },
  { question: "&lt; means:", options: [">", "<", "&", "\""], answer: "B" },
  { question: "&gt; means:", options: ["<", ">", "&", "\""], answer: "B" },
  { question: "&amp; means:", options: ["&", "<", ">", "Space"], answer: "A" },
  { question: "Hosting means:", options: ["Designing website", "Uploading website online", "Coding", "Styling"], answer: "B" },
  { question: "GitHub Pages is:", options: ["Browser", "Hosting service", "Email tool", "Database"], answer: "B" },
  { question: "Wix is:", options: ["Programming language", "Website builder", "Antivirus", "Protocol"], answer: "B" }
];